prompt Importing table BR_BROKERREWARDPROPS...
set feedback off
set define off
insert into BR_BROKERREWARDPROPS (MODULEID, REWARDTYPE, BROKERID, COMMODITYID, REWARDRATE, FIRSTPAYRATE, SECONDPAYRATE)
values (-1, 0, '-1', '-1', 0.8000, 0.2200, 0.7800);

insert into BR_BROKERREWARDPROPS (MODULEID, REWARDTYPE, BROKERID, COMMODITYID, REWARDRATE, FIRSTPAYRATE, SECONDPAYRATE)
values (15, 0, '1', 'Tio2', 0.0100, 0.0050, 0.9950);

insert into BR_BROKERREWARDPROPS (MODULEID, REWARDTYPE, BROKERID, COMMODITYID, REWARDRATE, FIRSTPAYRATE, SECONDPAYRATE)
values (15, 0, '666', 'Tio2', 0.8500, 1.0000, 0.0000);

prompt Done.
