prompt Importing table F_SUMMARY...
set feedback off
set define off
insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('40007', '发售付佣金', 'Income_I', 'C', '20030140', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('40009', '发售收保险费', 'SellOtherItem_I', 'D', '200240*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('40001', '发售收交易手续费', 'TradeFee_I', 'D', '20030140', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('40008', '发售收托管费', 'SellOtherItem_I', 'D', '200240*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('40010', '发售收仓储费', 'SellOtherItem_I', 'D', '200240*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('40011', '发售收清算费', 'SellOtherItem_I', 'D', '200240*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('40012', '发售收所得税', 'SellOtherItem_I', 'D', '200240*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('40013', '发售提货单注册费', 'DeliveryGoods_I', 'D', '200240*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('40014', '发售提货单注销费', 'DeliveryGoods_I', 'D', '200240*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('40015', '发售提货单过户费', 'DeliveryGoods_I', 'D', '200240*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('40002', '发售收发行手续费', 'TradeFee_I', 'D', '20030140', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('40016', '发售提货单配送费', 'DeliveryGoods_I', 'D', '200240*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('40006', '发售付交易商货款', 'Income_I', 'C', '200240*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('40005', '发售收交易商货款', 'Payout_I', 'D', '200240*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('11001', '交易商入金', 'Deposit', 'C', null, 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('11002', '交易商出金', 'Fetch', 'D', null, 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('11003', '银转入金', 'Deposit', 'C', 'spec', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('11004', '银转出金', 'Fetch', 'D', 'spec', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('11005', '代收银转手续费', 'BankFee', 'D', '200303', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('11006', '结转代收银转手续费', null, 'N', null, 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('11007', '发生银行费用', null, 'N', null, 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('11011', '计提风险准备金', null, 'N', null, 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('11012', '冲抵风险准备金', 'OtherItem', 'N', null, 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('11013', '收抵押手续费', null, 'N', null, 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('11014', '结转代收质押手续费', null, 'N', null, 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('11015', '代收仓储费', null, 'N', null, 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('11016', '结转交收代收仓储费', null, 'N', null, 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('11017', '发生银行利息', null, 'N', null, 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('11018', '付交易商存款利息', 'OtherItem', 'C', '2007', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('11019', '内部结转', null, 'N', null, 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15100', '交收收交易商税费', 'OtherItem_T', 'D', '100515*', 'N', 'N');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15101', '交收退交易商税费', 'OtherItem_T', 'C', '100515*', 'N', 'N');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15001', '订单收交易手续费', 'TradeFee_T', 'D', '20030115', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15002', '订单收交易保证金', 'Margin_T', 'D', '200215*', 'W', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15003', '订单退交易保证金', 'Margin_T', 'C', '200215*', 'W', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15004', '订单收浮亏', 'FL_T', 'D', '200215*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15005', '订单退浮亏', 'FL_T', 'C', '200215*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15006', '订单付交易盈利', 'TradePL_T', 'C', '200215*', 'T', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15007', '订单收交易亏损', 'TradePL_T', 'D', '200215*', 'T', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15008', '订单收交易商货款', 'Payout_T', 'D', '200215*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15009', '订单付交易商货款', 'Income_T', 'C', '200215*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15010', '订单收交收手续费', 'SettleFee_T', 'D', '20030215', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15011', '订单付交收盈利', 'SettlePL_T', 'C', '200215*', 'T', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15012', '订单收交收亏损', 'SettlePL_T', 'D', '200215*', 'T', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15013', '订单收交收保证金', 'SettleMargin_T', 'D', '200215*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15014', '订单退交收保证金', 'SettleMargin_T', 'C', '200215*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15015', '订单收净浮亏', 'FL_T', 'D', '200215$', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15016', '订单退净浮亏', 'FL_T', 'C', '200215$', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15017', '订单收违约金', 'OtherItem_T', 'D', '200415*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15018', '订单退违约金', 'OtherItem_T', 'C', '200415*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15019', '订单付佣金', 'Income_T', 'C', '20030115', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15020', '订单收延期补偿费', 'SettleCompens_T', 'D', '200515*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15021', '订单付延期补偿费', 'SettleCompens_T', 'C', '200515*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15022', '订单结转交易手续费', null, 'N', null, 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15023', '订单结转交收手续费', null, 'N', null, 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15094', '订单退交易商担保金', null, 'C', '209915*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15095', '订单收交易商担保金', null, 'D', '209915*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15096', '订单出担保金', null, 'N', null, 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15097', '订单入担保金', null, 'N', null, 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15098', '订单返增值税', null, 'N', '1005*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('15099', '订单收增值税', null, 'N', '1005*', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('23001', '现货收交易手续费', 'TradeFee_E', 'D', '20030123', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('23002', '现货收履约保证金', 'Margin_E', 'D', '200223', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('23003', '现货退履约保证金', 'MarginBack_E', 'C', '200223', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('23004', '现货收交收手续费', 'SettleFee_E', 'D', '20030223', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('23005', '现货收交易商货款', 'Payout_E', 'D', '200223', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('23006', '现货付交易商货款', 'Income_E', 'C', '200223', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('23010', '现货收违约金', 'OtherItem_E', 'D', '200423', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('23011', '现货付违约金', 'OtherItem_E', 'C', '200423', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('23012', '现货余额转诚信保障金', 'Subscirption_E', 'D', '200800#', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('23013', '现货诚信保障金转余额', 'Subscirption_E', 'C', '200800#', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('21001', '竞价收交易手续费', 'TradeFee_V', 'D', '20030121', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('21002', '竞价收交易保证金', 'Margin_V', 'D', '200221', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('21003', '竞价退交易保证金', 'Margin_V', 'C', '200221', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('21004', '竞价收交易商货款', 'Payout_V', 'D', '200221', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('21005', '竞价付交易商货款', 'Income_V', 'C', '200221', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('21016', '竞价收违约金', 'Payout_V', 'D', '200221', 'N', 'Y');

insert into F_SUMMARY (SUMMARYNO, SUMMARY, LEDGERITEM, FUNDDCFLAG, ACCOUNTCODEOPP, APPENDACCOUNT, ISINIT)
values ('21017', '竞价付违约金', 'Income_V', 'C', '200221', 'N', 'Y');
commit;

prompt Done.
