prompt Importing table M_PROPERTY...
set feedback off
set define off
insert into M_PROPERTY (PROPERTYID, CATEGORYID, PROPERTYNAME, HASVALUEDICT, STOCKCHECK, SEARCHABLE, SORTNO, ISNECESSARY, FIELDTYPE, PROPERTYTYPEID)
values (1030, 1028, '产地', 'Y', 'Y', 'Y', 2, 'Y', 0, 121);

insert into M_PROPERTY (PROPERTYID, CATEGORYID, PROPERTYNAME, HASVALUEDICT, STOCKCHECK, SEARCHABLE, SORTNO, ISNECESSARY, FIELDTYPE, PROPERTYTYPEID)
values (1031, 1028, '规格', 'Y', 'Y', 'Y', 3, 'Y', 0, 121);

insert into M_PROPERTY (PROPERTYID, CATEGORYID, PROPERTYNAME, HASVALUEDICT, STOCKCHECK, SEARCHABLE, SORTNO, ISNECESSARY, FIELDTYPE, PROPERTYTYPEID)
values (1028, 1020, '品牌', 'Y', 'M', 'Y', 2, 'Y', 0, 121);

insert into M_PROPERTY (PROPERTYID, CATEGORYID, PROPERTYNAME, HASVALUEDICT, STOCKCHECK, SEARCHABLE, SORTNO, ISNECESSARY, FIELDTYPE, PROPERTYTYPEID)
values (1029, 1028, '等级', 'Y', 'Y', 'Y', 1, 'Y', 0, 122);

insert into M_PROPERTY (PROPERTYID, CATEGORYID, PROPERTYNAME, HASVALUEDICT, STOCKCHECK, SEARCHABLE, SORTNO, ISNECESSARY, FIELDTYPE, PROPERTYTYPEID)
values (1032, 1028, '品牌', 'Y', 'Y', 'Y', 4, 'Y', 0, 121);

insert into M_PROPERTY (PROPERTYID, CATEGORYID, PROPERTYNAME, HASVALUEDICT, STOCKCHECK, SEARCHABLE, SORTNO, ISNECESSARY, FIELDTYPE, PROPERTYTYPEID)
values (1033, 1025, '产地', 'Y', 'Y', 'Y', 1, 'Y', 0, 121);

insert into M_PROPERTY (PROPERTYID, CATEGORYID, PROPERTYNAME, HASVALUEDICT, STOCKCHECK, SEARCHABLE, SORTNO, ISNECESSARY, FIELDTYPE, PROPERTYTYPEID)
values (1034, 1025, '等级', 'Y', 'Y', 'Y', 2, 'Y', 0, 121);

insert into M_PROPERTY (PROPERTYID, CATEGORYID, PROPERTYNAME, HASVALUEDICT, STOCKCHECK, SEARCHABLE, SORTNO, ISNECESSARY, FIELDTYPE, PROPERTYTYPEID)
values (1024, 1023, '级别', 'Y', 'Y', 'Y', 1, 'Y', 0, 120);

insert into M_PROPERTY (PROPERTYID, CATEGORYID, PROPERTYNAME, HASVALUEDICT, STOCKCHECK, SEARCHABLE, SORTNO, ISNECESSARY, FIELDTYPE, PROPERTYTYPEID)
values (1035, 1025, '品牌', 'Y', 'Y', 'Y', 3, 'Y', 0, 121);

insert into M_PROPERTY (PROPERTYID, CATEGORYID, PROPERTYNAME, HASVALUEDICT, STOCKCHECK, SEARCHABLE, SORTNO, ISNECESSARY, FIELDTYPE, PROPERTYTYPEID)
values (1040, 1000, '产地', 'Y', 'Y', 'Y', 1, 'Y', 0, 121);

insert into M_PROPERTY (PROPERTYID, CATEGORYID, PROPERTYNAME, HASVALUEDICT, STOCKCHECK, SEARCHABLE, SORTNO, ISNECESSARY, FIELDTYPE, PROPERTYTYPEID)
values (1023, 1022, '新旧程度', 'Y', 'Y', 'Y', 1, 'Y', 0, 120);

insert into M_PROPERTY (PROPERTYID, CATEGORYID, PROPERTYNAME, HASVALUEDICT, STOCKCHECK, SEARCHABLE, SORTNO, ISNECESSARY, FIELDTYPE, PROPERTYTYPEID)
values (1060, 1000, '年份', 'Y', 'Y', 'Y', 2, 'Y', 0, 121);

insert into M_PROPERTY (PROPERTYID, CATEGORYID, PROPERTYNAME, HASVALUEDICT, STOCKCHECK, SEARCHABLE, SORTNO, ISNECESSARY, FIELDTYPE, PROPERTYTYPEID)
values (1027, 1020, '产地', 'Y', 'M', 'Y', 1, 'Y', 0, 121);
commit;

prompt Done.
