/*
Navicat Oracle Data Transfer
Oracle Client Version : 12.1.0.2.0

Source Server         : 10.0.100.183-commo
Source Server Version : 110200
Source Host           : 10.0.100.183:1521
Source Schema         : TRADE_GNNT

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2016-03-12 21:50:13
*/


-- ----------------------------
-- Table structure for IPO_CHARGE_ITEM
-- ----------------------------
DROP TABLE "TRADE_GNNT"."IPO_CHARGE_ITEM";
CREATE TABLE "TRADE_GNNT"."IPO_CHARGE_ITEM" (
"ID" VARCHAR2(100 BYTE) NOT NULL ,
"NAME" VARCHAR2(100 BYTE) DEFAULT ''  NULL ,
"TYPE" NUMBER(1) NULL ,
"PARENT_ID" VARCHAR2(100 BYTE) DEFAULT 0  NULL ,
"SORT_ID" NUMBER(5) NULL ,
"REMARK" VARCHAR2(200 BYTE) NULL ,
"DELETE_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"LEAF" CHAR(1 BYTE) NULL ,
"CREATE_USER" VARCHAR2(32 BYTE) NULL ,
"CREATE_DATE" DATE NULL ,
"UPDATE_USER" VARCHAR2(32 BYTE) NULL ,
"UPDATE_DATE" DATE NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "TRADE_GNNT"."IPO_CHARGE_ITEM" IS '费用配置';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ITEM"."ID" IS '费用编码';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ITEM"."NAME" IS '费用名称';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ITEM"."TYPE" IS '费用类型,1:一次性费用,2:周期性费用';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ITEM"."PARENT_ID" IS '上级费用编码';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ITEM"."SORT_ID" IS '排序';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ITEM"."REMARK" IS '备注';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ITEM"."DELETE_FLAG" IS '删除标记 0:有效 1:无效';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ITEM"."LEAF" IS '是否叶子节点';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ITEM"."CREATE_USER" IS '创建人';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ITEM"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ITEM"."UPDATE_USER" IS '修改人';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ITEM"."UPDATE_DATE" IS '修改时间';

-- ----------------------------
-- Records of IPO_CHARGE_ITEM
-- ----------------------------
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_ITEM" VALUES ('003003', '提单过户费', '1', '003', '1', '提单过户费', '0', '1', 'hl', TO_DATE('2016-01-15 14:54:46', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_ITEM" VALUES ('003002', '提单注销费', '1', '003', '1', '提货单注销费', '0', '1', 'hl', TO_DATE('2016-01-15 14:54:46', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_ITEM" VALUES ('004003', '托管费', '1', '004', '3', '托管费', '0', '1', 'hl', TO_DATE('2016-01-15 14:54:46', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_ITEM" VALUES ('004002', '保险费', '1', '004', '2', '保险费', '0', '1', 'hl', TO_DATE('2016-01-15 14:54:46', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_ITEM" VALUES ('004001', '仓储费', '1', '004', '1', '仓储费', '0', '1', 'hl', TO_DATE('2016-01-15 14:54:46', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_ITEM" VALUES ('003001', '提单注册费', '1', '003', '1', '提货单注册费', '0', '1', 'hl', TO_DATE('2016-01-15 14:54:46', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_ITEM" VALUES ('003004', '提单配送费', '1', '003', '1', '提单配送费', '0', '1', 'hl', TO_DATE('2016-01-15 14:54:46', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_ITEM" VALUES ('001', '手续费', '1', '0', '1', '手续费', '0', '1', 'hl', TO_DATE('2016-01-15 14:54:46', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_ITEM" VALUES ('002', '货款', '1', '0', '2', '货款', '0', '1', 'hl', TO_DATE('2016-01-15 14:54:46', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_ITEM" VALUES ('003', '交收费用', '1', '0', '3', '交收费用', '0', '0', 'hl', TO_DATE('2016-01-15 14:54:46', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_ITEM" VALUES ('004', '仓库费用', '1', '0', '4', '仓库费用', '0', '0', 'hl', TO_DATE('2016-01-15 14:54:46', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_ITEM" VALUES ('005', '挂牌费', '1', '0', '5', '挂牌费', '0', '1', 'hl', TO_DATE('2016-01-15 14:54:46', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_ITEM" VALUES ('006', '佣金', '1', '0', '6', '佣金', '0', '1', 'hl', TO_DATE('2016-01-15 14:54:46', 'YYYY-MM-DD HH24:MI:SS'), 'sc', TO_DATE('2016-01-27 20:27:55', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_ITEM" VALUES ('007', '其他费', '1', '0', '7', '其他费', '0', '1', 'hl', TO_DATE('2016-01-15 14:54:46', 'YYYY-MM-DD HH24:MI:SS'), null, null);

-- ----------------------------
-- Table structure for IPO_CHARGE_ROLE
-- ----------------------------
DROP TABLE "TRADE_GNNT"."IPO_CHARGE_ROLE";
CREATE TABLE "TRADE_GNNT"."IPO_CHARGE_ROLE" (
"ID" NUMBER NOT NULL ,
"BUSINESS_CODE" VARCHAR2(50 BYTE) NULL ,
"ROLE_CODE" VARCHAR2(50 BYTE) NULL ,
"CHARGE_ID" VARCHAR2(100 BYTE) NULL ,
"CHARGE_PATTERN" NUMBER(1) NULL ,
"AMOUNT" NUMBER(15,3) NULL ,
"DELETE_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"CREATE_USER" VARCHAR2(32 BYTE) NULL ,
"CREATE_DATE" DATE NULL ,
"UPDATE_USER" VARCHAR2(32 BYTE) NULL ,
"UPDATE_DATE" DATE NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "TRADE_GNNT"."IPO_CHARGE_ROLE" IS '通用费用配置表';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ROLE"."ID" IS '主键 SEQ_IPO_CHARGE_ROLE';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ROLE"."BUSINESS_CODE" IS '业务代码';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ROLE"."ROLE_CODE" IS '角色代码';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ROLE"."CHARGE_ID" IS '费用项';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ROLE"."CHARGE_PATTERN" IS '收费模式 ,1:百分比 2:固定值';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ROLE"."AMOUNT" IS '金额';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ROLE"."DELETE_FLAG" IS '删除标记 ,0:未删除，1:已删除';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ROLE"."CREATE_USER" IS '创建人';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ROLE"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ROLE"."UPDATE_USER" IS '修改人';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_ROLE"."UPDATE_DATE" IS '修改时间';

-- ----------------------------
-- Records of IPO_CHARGE_ROLE
-- ----------------------------
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_ROLE" VALUES ('41', '002', '002', '010', '1', '0.20', '0', '1', TO_DATE('2016-01-25 21:03:36', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_ROLE" VALUES ('42', '006', '005', '002', '2', '100', '0', 'sc', TO_DATE('2016-01-27 10:26:14', 'YYYY-MM-DD HH24:MI:SS'), null, null);

-- ----------------------------
-- Table structure for IPO_CHARGE_USER
-- ----------------------------
DROP TABLE "TRADE_GNNT"."IPO_CHARGE_USER";
CREATE TABLE "TRADE_GNNT"."IPO_CHARGE_USER" (
"ID" NUMBER NOT NULL ,
"BUSINESS_CODE" VARCHAR2(50 BYTE) NULL ,
"ROLE_CODE" VARCHAR2(50 BYTE) NULL ,
"USER_ID" VARCHAR2(32 BYTE) NULL ,
"CHARGE_ID" VARCHAR2(100 BYTE) NULL ,
"CHARGE_PATTERN" NUMBER(1) NULL ,
"AMOUNT" NUMBER(15,3) NULL ,
"DELETE_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"CREATE_USER" VARCHAR2(32 BYTE) NULL ,
"CREATE_DATE" DATE NULL ,
"UPDATE_USER" VARCHAR2(32 BYTE) NULL ,
"UPDATE_DATE" DATE NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "TRADE_GNNT"."IPO_CHARGE_USER" IS '特殊费用配置表';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_USER"."ID" IS '主键 SEQ_IPO_CHARGE_USER';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_USER"."BUSINESS_CODE" IS '业务代码';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_USER"."ROLE_CODE" IS '角色代码';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_USER"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_USER"."CHARGE_ID" IS '费用项';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_USER"."CHARGE_PATTERN" IS '收费模式 ,1:百分比 2:固定值';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_USER"."AMOUNT" IS '金额';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_USER"."DELETE_FLAG" IS '删除标记 ,0:未删除，1:已删除';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_USER"."CREATE_USER" IS '创建人';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_USER"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_USER"."UPDATE_USER" IS '修改人';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_CHARGE_USER"."UPDATE_DATE" IS '修改时间';

-- ----------------------------
-- Records of IPO_CHARGE_USER
-- ----------------------------
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_USER" VALUES ('81', '001', '001', 'hl', '003002', '2', '100', '0', 'hl', TO_DATE('2016-03-08 10:30:32', 'YYYY-MM-DD HH24:MI:SS'), 'hl', TO_DATE('2016-03-08 10:30:56', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_USER" VALUES ('82', '003', '003', 'SC', '003001', '2', '2', '0', 'hl', TO_DATE('2016-03-08 10:31:45', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_USER" VALUES ('42', '006', '005', 'hl', '009', '2', '1000', '0', 'sc', TO_DATE('2016-01-25 11:18:12', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_USER" VALUES ('43', '006', '005', 'sc', '009', '2', '1000', '0', 'sc', TO_DATE('2016-01-25 11:18:34', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_USER" VALUES ('44', '006', '005', '没有的用户', '007', '2', '100', '0', 'sc', TO_DATE('2016-01-27 10:25:12', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_USER" VALUES ('45', '006', '002', 'SC', '010', '2', '10', '0', 'sc', TO_DATE('2016-01-27 10:42:42', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_USER" VALUES ('46', '006', '005', 'SC', '007', '2', '6666', '0', 'sc', TO_DATE('2016-01-27 10:54:47', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_USER" VALUES ('47', '006', '005', 'SC', '001', '2', '666', '0', 'sc', TO_DATE('2016-01-27 20:19:23', 'YYYY-MM-DD HH24:MI:SS'), null, null);
INSERT INTO "TRADE_GNNT"."IPO_CHARGE_USER" VALUES ('61', '002', '002', 'sc', '001', '1', '1', '0', 'chenj', TO_DATE('2016-02-26 14:12:01', 'YYYY-MM-DD HH24:MI:SS'), null, null);

-- ----------------------------
-- Table structure for IPO_CLEARSTATUS
-- ----------------------------
DROP TABLE "TRADE_GNNT"."IPO_CLEARSTATUS";
CREATE TABLE "TRADE_GNNT"."IPO_CLEARSTATUS" (
"ACTIONID" NUMBER(3) NOT NULL ,
"ACTIONNOTE" VARCHAR2(32 BYTE) NOT NULL ,
"STATUS" CHAR(1 BYTE) NOT NULL ,
"FINISHTIME" DATE NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of IPO_CLEARSTATUS
-- ----------------------------
INSERT INTO "TRADE_GNNT"."IPO_CLEARSTATUS" VALUES ('0', '结算开始', 'Y', TO_DATE('2016-03-12 19:48:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "TRADE_GNNT"."IPO_CLEARSTATUS" VALUES ('1', '扣发行手续费,扣托管商品的手续费', 'Y', TO_DATE('2016-03-12 19:48:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "TRADE_GNNT"."IPO_CLEARSTATUS" VALUES ('2', '扣增发的货款,扣增发的手续费', 'Y', TO_DATE('2016-03-12 19:48:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "TRADE_GNNT"."IPO_CLEARSTATUS" VALUES ('3', '扣发售的货款,扣发售的手续费', 'Y', TO_DATE('2016-03-12 19:48:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "TRADE_GNNT"."IPO_CLEARSTATUS" VALUES ('4', '扣过户费', 'Y', TO_DATE('2016-03-12 19:48:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "TRADE_GNNT"."IPO_CLEARSTATUS" VALUES ('5', '扣仓储费,仓库保险费,仓库托管费', 'Y', TO_DATE('2016-03-12 19:48:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "TRADE_GNNT"."IPO_CLEARSTATUS" VALUES ('6', '佣金结算', 'Y', TO_DATE('2016-03-12 19:48:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "TRADE_GNNT"."IPO_CLEARSTATUS" VALUES ('7', '结算完成', 'Y', TO_DATE('2016-03-12 19:48:25', 'YYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for IPO_NOTTRADEDAY
-- ----------------------------
DROP TABLE "TRADE_GNNT"."IPO_NOTTRADEDAY";
CREATE TABLE "TRADE_GNNT"."IPO_NOTTRADEDAY" (
"ID" NUMBER(10) NOT NULL ,
"WEEK" VARCHAR2(30 BYTE) NULL ,
"DAY" VARCHAR2(1024 BYTE) NULL ,
"MODIFYTIME" DATE NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "TRADE_GNNT"."IPO_NOTTRADEDAY"."WEEK" IS '星期几';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_NOTTRADEDAY"."DAY" IS '日期';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_NOTTRADEDAY"."MODIFYTIME" IS '修改时间';

-- ----------------------------
-- Records of IPO_NOTTRADEDAY
-- ----------------------------
INSERT INTO "TRADE_GNNT"."IPO_NOTTRADEDAY" VALUES ('1', null, '2008-10-01,2008-10-02,2008-10-03,2015-11-30,2015-11-22', TO_DATE('2016-03-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for IPO_SYSSTATUS
-- ----------------------------
DROP TABLE "TRADE_GNNT"."IPO_SYSSTATUS";
CREATE TABLE "TRADE_GNNT"."IPO_SYSSTATUS" (
"TRADEDATE" DATE NOT NULL ,
"STATUS" NUMBER(2) DEFAULT 3  NOT NULL ,
"SECTIONID" NUMBER(4) NULL ,
"NOTE" VARCHAR2(256 BYTE) NULL ,
"RECOVERTIME" VARCHAR2(10 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of IPO_SYSSTATUS
-- ----------------------------
INSERT INTO "TRADE_GNNT"."IPO_SYSSTATUS" VALUES (TO_DATE('2016-03-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '5', '223', '交易中', null);

-- ----------------------------
-- Table structure for IPO_TRADETIME
-- ----------------------------
DROP TABLE "TRADE_GNNT"."IPO_TRADETIME";
CREATE TABLE "TRADE_GNNT"."IPO_TRADETIME" (
"SECTIONID" NUMBER(4) NOT NULL ,
"NAME" VARCHAR2(20 BYTE) NULL ,
"STARTTIME" VARCHAR2(10 BYTE) NOT NULL ,
"ENDTIME" VARCHAR2(10 BYTE) NOT NULL ,
"STATUS" NUMBER(2) NOT NULL ,
"MODIFYTIME" DATE NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "TRADE_GNNT"."IPO_TRADETIME"."SECTIONID" IS 'ID';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_TRADETIME"."NAME" IS '交易节名称';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_TRADETIME"."STARTTIME" IS '开始时间';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_TRADETIME"."ENDTIME" IS '结束时间';
COMMENT ON COLUMN "TRADE_GNNT"."IPO_TRADETIME"."STATUS" IS '状态
0:有效
1:无效';

-- ----------------------------
-- Records of IPO_TRADETIME
-- ----------------------------
INSERT INTO "TRADE_GNNT"."IPO_TRADETIME" VALUES ('221', '早盘', '08:00:00', '11:00:00', '1', TO_DATE('2016-03-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "TRADE_GNNT"."IPO_TRADETIME" VALUES ('222', '午盘', '14:00:00', '17:00:00', '1', TO_DATE('2016-03-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "TRADE_GNNT"."IPO_TRADETIME" VALUES ('223', '晚盘', '19:00:00', '22:00:00', '1', TO_DATE('2016-03-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Indexes structure for table IPO_CHARGE_ITEM
-- ----------------------------
CREATE INDEX "TRADE_GNNT"."IND_IPO_CHARGE_DELETE_FLAG"
ON "TRADE_GNNT"."IPO_CHARGE_ITEM" ("DELETE_FLAG" ASC)
LOGGING
VISIBLE;
CREATE INDEX "TRADE_GNNT"."IND_IPO_CHARGE_PARENT_ID"
ON "TRADE_GNNT"."IPO_CHARGE_ITEM" ("PARENT_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "TRADE_GNNT"."IND_IPO_CHARGE_SORT_ID"
ON "TRADE_GNNT"."IPO_CHARGE_ITEM" ("SORT_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "TRADE_GNNT"."IND_IPO_CHARGE_TYPE"
ON "TRADE_GNNT"."IPO_CHARGE_ITEM" ("TYPE" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table IPO_CHARGE_ITEM
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."IPO_CHARGE_ITEM" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table IPO_CHARGE_ITEM
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."IPO_CHARGE_ITEM" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table IPO_CHARGE_ROLE
-- ----------------------------
CREATE INDEX "TRADE_GNNT"."IND_IPO_CHARGE_ROLE_DELETEFLAG"
ON "TRADE_GNNT"."IPO_CHARGE_ROLE" ("DELETE_FLAG" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table IPO_CHARGE_ROLE
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."IPO_CHARGE_ROLE" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table IPO_CHARGE_ROLE
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."IPO_CHARGE_ROLE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table IPO_CHARGE_USER
-- ----------------------------
CREATE INDEX "TRADE_GNNT"."IND_IPO_CHARGE_USER_DELETEFLAG"
ON "TRADE_GNNT"."IPO_CHARGE_USER" ("DELETE_FLAG" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table IPO_CHARGE_USER
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."IPO_CHARGE_USER" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table IPO_CHARGE_USER
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."IPO_CHARGE_USER" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table IPO_CLEARSTATUS
-- ----------------------------

-- ----------------------------
-- Checks structure for table IPO_CLEARSTATUS
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."IPO_CLEARSTATUS" ADD CHECK ("ACTIONID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."IPO_CLEARSTATUS" ADD CHECK ("ACTIONNOTE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."IPO_CLEARSTATUS" ADD CHECK ("STATUS" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table IPO_CLEARSTATUS
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."IPO_CLEARSTATUS" ADD PRIMARY KEY ("ACTIONID");

-- ----------------------------
-- Indexes structure for table IPO_NOTTRADEDAY
-- ----------------------------

-- ----------------------------
-- Checks structure for table IPO_NOTTRADEDAY
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."IPO_NOTTRADEDAY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."IPO_NOTTRADEDAY" ADD CHECK ("MODIFYTIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table IPO_NOTTRADEDAY
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."IPO_NOTTRADEDAY" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table IPO_SYSSTATUS
-- ----------------------------

-- ----------------------------
-- Checks structure for table IPO_SYSSTATUS
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."IPO_SYSSTATUS" ADD CHECK ("TRADEDATE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."IPO_SYSSTATUS" ADD CHECK ("STATUS" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table IPO_SYSSTATUS
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."IPO_SYSSTATUS" ADD PRIMARY KEY ("TRADEDATE");

-- ----------------------------
-- Indexes structure for table IPO_TRADETIME
-- ----------------------------

-- ----------------------------
-- Checks structure for table IPO_TRADETIME
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."IPO_TRADETIME" ADD CHECK ("SECTIONID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."IPO_TRADETIME" ADD CHECK ("STARTTIME" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."IPO_TRADETIME" ADD CHECK ("ENDTIME" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."IPO_TRADETIME" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."IPO_TRADETIME" ADD CHECK ("MODIFYTIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table IPO_TRADETIME
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."IPO_TRADETIME" ADD PRIMARY KEY ("SECTIONID");
